"""add unique constraint on sessions.name

Revision ID: 4fd42b663b3e
Revises: 6a1f2519e990
Create Date: 2026-03-02 17:17:33.758275
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4fd42b663b3e'
down_revision: str | None = '6a1f2519e990'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sessions', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='unique')
    # ### end Alembic commands ###
