"""add max_leverage to instruments

Revision ID: 6a1f2519e990
Revises: 76f6b651fb6d
Create Date: 2026-03-02 17:12:47.269584
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6a1f2519e990'
down_revision: str | None = '76f6b651fb6d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('max_leverage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'max_leverage')
    # ### end Alembic commands ###
