"""create Phase 1 schema

Revision ID: 76f6b651fb6d
Revises: 
Create Date: 2026-03-02 14:11:44.291810
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76f6b651fb6d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brokers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market_type', sa.String(length=50), nullable=False),
    sa.Column('default_currency', sa.String(length=10), nullable=False),
    sa.Column('is_predefined', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('market_analysis_modules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_dual', sa.Boolean(), nullable=False),
    sa.Column('asset_a', sa.String(length=50), nullable=True),
    sa.Column('asset_b', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_utc', sa.Time(), nullable=False),
    sa.Column('end_utc', sa.Time(), nullable=False),
    sa.Column('is_point', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trading_styles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('default_timeframes', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('instruments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('broker_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('asset_class', sa.String(length=50), nullable=False),
    sa.Column('base_currency', sa.String(length=10), nullable=True),
    sa.Column('quote_currency', sa.String(length=10), nullable=True),
    sa.Column('pip_size', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('tick_value', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('min_lot', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('is_predefined', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_id', 'symbol')
    )
    op.create_table('market_analysis_indicators',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('module_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('asset_target', sa.String(length=10), nullable=False),
    sa.Column('tv_symbol', sa.String(length=100), nullable=False),
    sa.Column('tv_timeframe', sa.String(length=10), nullable=False),
    sa.Column('timeframe_level', sa.String(length=10), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('tooltip', sa.Text(), nullable=True),
    sa.Column('answer_bullish', sa.String(length=200), nullable=False),
    sa.Column('answer_partial', sa.String(length=200), nullable=False),
    sa.Column('answer_bearish', sa.String(length=200), nullable=False),
    sa.Column('default_enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['market_analysis_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'key')
    )
    op.create_index('idx_ma_indicators_level', 'market_analysis_indicators', ['module_id', 'timeframe_level'], unique=False)
    op.create_index('idx_ma_indicators_module', 'market_analysis_indicators', ['module_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('market_type', sa.String(length=50), nullable=False),
    sa.Column('broker_id', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('capital_start', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('capital_current', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('risk_percentage_default', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_concurrent_risk_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("market_type IN ('CFD', 'Crypto')", name='ck_profiles_market_type'),
    sa.CheckConstraint('capital_current > 0', name='ck_profiles_capital_current_positive'),
    sa.CheckConstraint('capital_start > 0', name='ck_profiles_capital_start_positive'),
    sa.CheckConstraint('max_concurrent_risk_pct > 0', name='ck_profiles_max_concurrent_risk_positive'),
    sa.CheckConstraint('risk_percentage_default > 0 AND risk_percentage_default <= 10', name='ck_profiles_risk_pct_range'),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal_progress_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('style_id', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('pnl_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('goal_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('limit_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('goal_hit', sa.Boolean(), nullable=False),
    sa.Column('limit_hit', sa.Boolean(), nullable=False),
    sa.Column('vi_multiplier', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('adjusted_goal', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('adjusted_limit', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['style_id'], ['trading_styles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_goal_progress_profile_period', 'goal_progress_log', ['profile_id', 'period_start'], unique=False)
    op.create_table('market_analysis_configs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=True),
    sa.Column('module_id', sa.BigInteger(), nullable=True),
    sa.Column('score_thresholds', postgresql.JSONB(astext_type=sa.Text()), server_default='{"bullish": 60, "bearish": 40}', nullable=False),
    sa.Column('risk_multipliers', postgresql.JSONB(astext_type=sa.Text()), server_default='{"bullish_long": 1.20, "bullish_short": 0.70, "bearish_long": 0.70, "bearish_short": 1.20}', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['market_analysis_modules.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_analysis_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('module_id', sa.BigInteger(), nullable=False),
    sa.Column('score_htf_a', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_mtf_a', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_ltf_a', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bias_htf_a', sa.String(length=10), nullable=True),
    sa.Column('bias_mtf_a', sa.String(length=10), nullable=True),
    sa.Column('bias_ltf_a', sa.String(length=10), nullable=True),
    sa.Column('score_htf_b', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_mtf_b', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_ltf_b', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bias_htf_b', sa.String(length=10), nullable=True),
    sa.Column('bias_mtf_b', sa.String(length=10), nullable=True),
    sa.Column('bias_ltf_b', sa.String(length=10), nullable=True),
    sa.Column('news_sentiment', sa.String(length=10), nullable=True),
    sa.Column('news_confidence', sa.Integer(), nullable=True),
    sa.Column('news_summary', sa.Text(), nullable=True),
    sa.Column('news_key_themes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('news_risks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('news_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('news_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('news_provider', sa.String(length=20), nullable=True),
    sa.Column('news_model', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['market_analysis_modules.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ma_sessions_profile_module', 'market_analysis_sessions', ['profile_id', 'module_id', 'analyzed_at'], unique=False)
    op.create_table('news_provider_config',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=40), nullable=False),
    sa.Column('api_key_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('api_key_iv', sa.LargeBinary(), nullable=True),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('max_fetches_per_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_table('note_templates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('capital_start', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('capital_current', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('pnl_absolute', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('pnl_percent', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('win_count', sa.Integer(), nullable=False),
    sa.Column('loss_count', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('equity_curve', postgresql.ARRAY(sa.Numeric(precision=20, scale=2)), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'snapshot_date')
    )
    op.create_index('idx_performance_snapshots_profile_date', 'performance_snapshots', ['profile_id', 'snapshot_date'], unique=False)
    op.create_table('profile_goals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('style_id', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('goal_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('limit_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('goal_pct > 0', name='ck_profile_goals_goal_pct_positive'),
    sa.CheckConstraint('limit_pct < 0', name='ck_profile_goals_limit_pct_negative'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['style_id'], ['trading_styles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'style_id', 'period')
    )
    op.create_index('idx_profile_goals_profile', 'profile_goals', ['profile_id'], unique=False)
    op.create_table('profile_indicator_config',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('indicator_id', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['market_analysis_indicators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'indicator_id')
    )
    op.create_table('strategies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('trades_count', sa.Integer(), nullable=False),
    sa.Column('win_count', sa.Integer(), nullable=False),
    sa.Column('min_trades_for_stats', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('min_trades_for_stats >= 1', name='ck_strategies_min_trades'),
    sa.CheckConstraint('trades_count >= 0', name='ck_strategies_trades_count'),
    sa.CheckConstraint('win_count <= trades_count', name='ck_strategies_win_lte_trades'),
    sa.CheckConstraint('win_count >= 0', name='ck_strategies_win_count'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'name')
    )
    op.create_index('idx_strategies_profile', 'strategies', ['profile_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'name')
    )
    op.create_index('idx_tags_profile', 'tags', ['profile_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('analyzed_tf_list', postgresql.JSONB(astext_type=sa.Text()), server_default='["15m","1h","4h","1d","1w"]', nullable=False),
    sa.Column('news_intelligence_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_style', sa.String(length=20), nullable=True),
    sa.Column('last_period', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_table('weekly_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('impact', sa.String(length=10), nullable=False),
    sa.Column('asset_scope', postgresql.ARRAY(sa.Text()), server_default='{"all"}', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("impact IN ('high', 'medium', 'low')", name='ck_weekly_events_impact'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_weekly_events_date_impact', 'weekly_events', ['event_date', 'impact'], unique=False)
    op.create_index('idx_weekly_events_profile_week', 'weekly_events', ['profile_id', 'week_start'], unique=False)
    op.create_table('market_analysis_answers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('indicator_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('answer_label', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['market_analysis_indicators.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['market_analysis_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'indicator_id')
    )
    op.create_index('idx_ma_answers_session', 'market_analysis_answers', ['session_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=True),
    sa.Column('strategy_id', sa.BigInteger(), nullable=True),
    sa.Column('market_analysis_session_id', sa.BigInteger(), nullable=True),
    sa.Column('pair', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('asset_class', sa.String(length=50), nullable=True),
    sa.Column('analyzed_timeframe', sa.String(length=10), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('nb_take_profits', sa.Integer(), nullable=False),
    sa.Column('risk_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('potential_profit', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('current_risk', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('market_vi_at_entry', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('pair_vi_at_entry', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('vi_adjusted_risk_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('auto_generated', sa.Boolean(), nullable=False),
    sa.Column('signal_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('slippage', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('commission', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('leverage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('spread', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('estimated_fees', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('session_tag', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('structured_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('screenshot_urls', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("(status = 'closed' AND realized_pnl IS NOT NULL) OR (status != 'closed' AND realized_pnl IS NULL)", name='ck_trades_pnl_consistency'),
    sa.CheckConstraint("direction IN ('long', 'short')", name='ck_trades_direction'),
    sa.CheckConstraint("status IN ('open', 'partial', 'closed')", name='ck_trades_status'),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 100)', name='ck_trades_confidence_score_range'),
    sa.CheckConstraint('nb_take_profits >= 1 AND nb_take_profits <= 3', name='ck_trades_nb_tp_range'),
    sa.CheckConstraint('potential_profit > 0', name='ck_trades_potential_profit_positive'),
    sa.CheckConstraint('risk_amount > 0', name='ck_trades_risk_amount_positive'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['market_analysis_session_id'], ['market_analysis_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trades_pair', 'trades', ['pair'], unique=False)
    op.create_index('idx_trades_profile_created', 'trades', ['profile_id', 'created_at'], unique=False)
    op.create_index('idx_trades_status', 'trades', ['status'], unique=False)
    op.create_index('idx_trades_strategy', 'trades', ['strategy_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('trade_id', sa.BigInteger(), nullable=False),
    sa.Column('position_number', sa.Integer(), nullable=False),
    sa.Column('take_profit_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('lot_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('exit_date', sa.DateTime(), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'closed' AND exit_price IS NOT NULL) OR (status != 'closed' AND exit_price IS NULL)", name='ck_positions_exit_price_consistency'),
    sa.CheckConstraint("status IN ('open', 'closed', 'cancelled')", name='ck_positions_status'),
    sa.CheckConstraint('lot_percentage > 0 AND lot_percentage <= 100', name='ck_positions_lot_pct_range'),
    sa.CheckConstraint('position_number IN (1, 2, 3)', name='ck_positions_number_range'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id', 'position_number')
    )
    op.create_index('idx_positions_status', 'positions', ['status'], unique=False)
    op.create_index('idx_positions_trade', 'positions', ['trade_id'], unique=False)
    op.create_table('trade_tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('trade_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id', 'tag_id')
    )
    op.create_index('idx_trade_tags_tag', 'trade_tags', ['tag_id'], unique=False)
    op.create_index('idx_trade_tags_trade', 'trade_tags', ['trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trade_tags_trade', table_name='trade_tags')
    op.drop_index('idx_trade_tags_tag', table_name='trade_tags')
    op.drop_table('trade_tags')
    op.drop_index('idx_positions_trade', table_name='positions')
    op.drop_index('idx_positions_status', table_name='positions')
    op.drop_table('positions')
    op.drop_index('idx_trades_strategy', table_name='trades')
    op.drop_index('idx_trades_status', table_name='trades')
    op.drop_index('idx_trades_profile_created', table_name='trades')
    op.drop_index('idx_trades_pair', table_name='trades')
    op.drop_table('trades')
    op.drop_index('idx_ma_answers_session', table_name='market_analysis_answers')
    op.drop_table('market_analysis_answers')
    op.drop_index('idx_weekly_events_profile_week', table_name='weekly_events')
    op.drop_index('idx_weekly_events_date_impact', table_name='weekly_events')
    op.drop_table('weekly_events')
    op.drop_table('user_preferences')
    op.drop_index('idx_tags_profile', table_name='tags')
    op.drop_table('tags')
    op.drop_index('idx_strategies_profile', table_name='strategies')
    op.drop_table('strategies')
    op.drop_table('profile_indicator_config')
    op.drop_index('idx_profile_goals_profile', table_name='profile_goals')
    op.drop_table('profile_goals')
    op.drop_index('idx_performance_snapshots_profile_date', table_name='performance_snapshots')
    op.drop_table('performance_snapshots')
    op.drop_table('note_templates')
    op.drop_table('news_provider_config')
    op.drop_index('idx_ma_sessions_profile_module', table_name='market_analysis_sessions')
    op.drop_table('market_analysis_sessions')
    op.drop_table('market_analysis_configs')
    op.drop_index('idx_goal_progress_profile_period', table_name='goal_progress_log')
    op.drop_table('goal_progress_log')
    op.drop_table('profiles')
    op.drop_index('idx_ma_indicators_module', table_name='market_analysis_indicators')
    op.drop_index('idx_ma_indicators_level', table_name='market_analysis_indicators')
    op.drop_table('market_analysis_indicators')
    op.drop_table('instruments')
    op.drop_table('trading_styles')
    op.drop_table('sessions')
    op.drop_table('market_analysis_modules')
    op.drop_table('brokers')
    # ### end Alembic commands ###
