"""add margin_used to trades

Revision ID: fe8288f1af1c
Revises: p3001_phase3_risk_management
Create Date: 2026-03-27 15:13:33.781315
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe8288f1af1c'
down_revision: Union[str, None] = 'p3001_phase3_risk_management'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goal_override_log', 'acknowledged',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('goal_progress_log', 'style_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(op.f('goal_progress_log_style_id_fkey'), 'goal_progress_log', type_='foreignkey')
    op.create_foreign_key(None, 'goal_progress_log', 'trading_styles', ['style_id'], ['id'])
    op.alter_column('market_analysis_indicators', 'score_block',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('market_vi_pairs', 'is_selected',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('market_vi_snapshots', 'components',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('market_vi_snapshots_timestamp_idx'), table_name='market_vi_snapshots')
    op.drop_index(op.f('ix_mvs_tf_ts'), table_name='market_vi_snapshots')
    op.create_index('ix_mvs_tf_ts', 'market_vi_snapshots', ['timeframe', 'timestamp'], unique=False)
    op.drop_column('market_vi_snapshots', 'id')
    op.alter_column('notification_settings', 'bots',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_settings', 'market_vi_alerts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_settings', 'watchlist_alerts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('profile_goals', 'period_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('profile_goals', 'show_on_dashboard',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('uq_profile_goals_global'), table_name='profile_goals', postgresql_where='(style_id IS NULL)')
    op.drop_index(op.f('uq_profile_goals_style'), table_name='profile_goals', postgresql_where='(style_id IS NOT NULL)')
    op.alter_column('profiles', 'trades_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('profiles', 'win_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('profiles', 'min_pnl_pct_for_stats',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('risk_settings', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('uq_strategies_global'), table_name='strategies', postgresql_where='(profile_id IS NULL)')
    op.drop_index(op.f('uq_strategies_profile'), table_name='strategies', postgresql_where='(profile_id IS NOT NULL)')
    op.add_column('trades', sa.Column('margin_used', sa.Numeric(precision=12, scale=2), nullable=True))
    op.alter_column('trades', 'order_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_trades_order_type'), table_name='trades')
    op.alter_column('volatility_settings', 'market_vi',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('volatility_settings', 'per_pair',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('volatility_settings', 'regimes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('volatility_snapshots', 'components',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('volatility_snapshots_timestamp_idx'), table_name='volatility_snapshots')
    op.drop_index(op.f('ix_vs_pair_tf_ts'), table_name='volatility_snapshots')
    op.create_index('ix_vs_pair_tf_ts', 'volatility_snapshots', ['pair', 'timeframe', 'timestamp'], unique=False)
    op.drop_index(op.f('ix_vs_vi_score_tf'), table_name='volatility_snapshots')
    op.create_index('ix_vs_vi_score_tf', 'volatility_snapshots', ['timeframe', 'vi_score'], unique=False)
    op.drop_column('volatility_snapshots', 'id')
    op.alter_column('watchlist_snapshots', 'pairs_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('watchlist_snapshots', 'pairs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_wls_tf_generated'), table_name='watchlist_snapshots')
    op.create_index('ix_wls_tf_generated', 'watchlist_snapshots', ['timeframe', 'generated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wls_tf_generated', table_name='watchlist_snapshots')
    op.create_index(op.f('ix_wls_tf_generated'), 'watchlist_snapshots', ['timeframe', sa.literal_column('generated_at DESC')], unique=False)
    op.alter_column('watchlist_snapshots', 'pairs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False)
    op.alter_column('watchlist_snapshots', 'pairs_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.add_column('volatility_snapshots', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.drop_index('ix_vs_vi_score_tf', table_name='volatility_snapshots')
    op.create_index(op.f('ix_vs_vi_score_tf'), 'volatility_snapshots', ['timeframe', sa.literal_column('vi_score DESC')], unique=False)
    op.drop_index('ix_vs_pair_tf_ts', table_name='volatility_snapshots')
    op.create_index(op.f('ix_vs_pair_tf_ts'), 'volatility_snapshots', ['pair', 'timeframe', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('volatility_snapshots_timestamp_idx'), 'volatility_snapshots', [sa.literal_column('timestamp DESC')], unique=False)
    op.alter_column('volatility_snapshots', 'components',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('volatility_settings', 'regimes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('volatility_settings', 'per_pair',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('volatility_settings', 'market_vi',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.create_index(op.f('idx_trades_order_type'), 'trades', ['order_type'], unique=False)
    op.alter_column('trades', 'order_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'MARKET'::character varying"),
               existing_nullable=False)
    op.drop_column('trades', 'margin_used')
    op.create_index(op.f('uq_strategies_profile'), 'strategies', ['profile_id', 'name'], unique=True, postgresql_where='(profile_id IS NOT NULL)')
    op.create_index(op.f('uq_strategies_global'), 'strategies', ['name'], unique=True, postgresql_where='(profile_id IS NULL)')
    op.alter_column('risk_settings', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('profiles', 'min_pnl_pct_for_stats',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               server_default=sa.text('0.100'),
               existing_nullable=False)
    op.alter_column('profiles', 'win_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('profiles', 'trades_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.create_index(op.f('uq_profile_goals_style'), 'profile_goals', ['profile_id', 'style_id', 'period', 'period_type'], unique=True, postgresql_where='(style_id IS NOT NULL)')
    op.create_index(op.f('uq_profile_goals_global'), 'profile_goals', ['profile_id', 'period', 'period_type'], unique=True, postgresql_where='(style_id IS NULL)')
    op.alter_column('profile_goals', 'show_on_dashboard',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('profile_goals', 'period_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'outcome'::character varying"),
               existing_nullable=False)
    op.alter_column('notification_settings', 'watchlist_alerts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('notification_settings', 'market_vi_alerts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('notification_settings', 'bots',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False)
    op.add_column('market_vi_snapshots', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.drop_index('ix_mvs_tf_ts', table_name='market_vi_snapshots')
    op.create_index(op.f('ix_mvs_tf_ts'), 'market_vi_snapshots', ['timeframe', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('market_vi_snapshots_timestamp_idx'), 'market_vi_snapshots', [sa.literal_column('timestamp DESC')], unique=False)
    op.alter_column('market_vi_snapshots', 'components',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('market_vi_pairs', 'is_selected',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('market_analysis_indicators', 'score_block',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'trend'::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'goal_progress_log', type_='foreignkey')
    op.create_foreign_key(op.f('goal_progress_log_style_id_fkey'), 'goal_progress_log', 'trading_styles', ['style_id'], ['id'], ondelete='CASCADE')
    op.alter_column('goal_progress_log', 'style_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('goal_override_log', 'acknowledged',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    # ### end Alembic commands ###
